import React, { ReactElement } from 'react'
import Head from 'next/head'
import Navbar from '../components/Nav'
import 'antd/dist/antd.css';
import '../styles/globals.css'
import type { AppProps /*, AppContext */ } from 'next/app'
import { Layout } from 'antd';

function MyApp({ Component, pageProps }: AppProps):ReactElement {
  const { Footer } = Layout;
  return (
    <>
    <Head>
        <title>Resume Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar/>
    <Component/>
    <Footer style={{ textAlign: 'center', backgroundColor: '#001529', color:'gray' }}>NextJS Portfolio ©2021 Created by Kamontip Koopiamrug</Footer>
    </>
  )
}

export default MyApp;
