import React from 'react'
import Head from 'next/head'
import Navbar from '../components/Nav'
import 'antd/dist/antd.css';
import '../styles/globals.css'
import styles from '../styles/Home.module.css';
import { Layout } from 'antd';

function MyApp({ Component, pageProps }) {
  const { Footer } = Layout;
  return (
    <>
    <Head>
        <title>Resume Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar/>
    <Component {...pageProps}/>
    <Footer style={{ textAlign: 'center' }}>NextJS Portfolio ©2021 Created by Kamontip Koopiamrug</Footer>
    </>
  )
}

export default MyApp
